### ISSUE TITLE
侧边栏推荐位红色 已经按照格式填写仍然无法显示推荐内容

### ISSUE THREAD

**Issue by thomas0612** [hiCasper/Typecho-theme-DUX#19]
侧边栏推荐位红色 已经按照格式填写仍然无法显示推荐内容
抄了示例的内容进去也无法显示

**Comment by caspershw** [comment]
检查一下有没有使用广告屏蔽插件，EasyList China规则里面会拦截 `.widget_ui_textasb` 这个class，我之前向官方反馈也无果。
