### ISSUE TITLE
首页懒加载第一屏图片不显示，要滚一下

### ISSUE THREAD

**Issue by am-abudu** [hiCasper/Typecho-theme-DUX#20]
首页懒加载第一屏图片不显示，要滚一下

**Comment by caspershw** [comment]
我这边没有遇到这样的问题，可能是你这边的偶然性bug。

**Comment by yuhao2348732** [comment]
你如果从别的网站下载的主题，看下Typecho-theme-DUX/img/banner.png，是不是文件名或者后缀不对，改成banner.png
