### ISSUE TITLE
评论提交后会提示  ”必须填写电子邮箱地址“

### ISSUE THREAD

**Issue by ChrisSun112** [hiCasper/Typecho-theme-DUX#3]
评论提交后会提示  ”必须填写电子邮箱地址“
解决方案参考 ：http://forum.typecho.org/viewtopic.php?f=5&t=9974&p=38595

**Comment by caspershw** [comment]
这个问题早在九月份就修复了。
https://github.com/hiCasper/Typecho-theme-DUX/commit/ced7314a847f2b0c496e7a66112fdefc221c2094

**Comment by wepad** [comment]
我也遇到了这个问题 还是没有修复，希望大神能帮忙看一下，[我的博客遇到的问题现象](http://comcom.f3322.net:4011/index.php/archives/4/)
