### ISSUE TITLE
手机端适配

### ISSUE THREAD

**Issue by yulianjie** [hiCasper/Typecho-theme-DUX#7]
手机端的评论没有适配，请问该怎么设置

**Comment by caspershw** [comment]
将 css/main.css 中 1669 行改为 `display: inline;` 即可

**Comment by yulianjie** [comment]
> 将 css/main.css 中 1669 行改为 `display: inline;` 即可

 大佬，有没有方法只改手机端的显示效果呢，就是自适应

**Comment by caspershw** [comment]
> > 将 css/main.css 中 1669 行改为 `display: inline;` 即可
> 
> 大佬，有没有方法只改手机端的显示效果呢，就是自适应

有这个打算，过段时间有空了就修复
