### ISSUE TITLE
分类多导致nav显示内容错乱

### ISSUE THREAD

**Issue by sunlianlong** [hiCasper/Typecho-theme-DUX#8]
后台设置了多级分类，但是首页默认展开成平级导致显示过多，样式错乱
![image](https://user-images.githubusercontent.com/22101668/56333934-c819d380-61c8-11e9-9bc3-1465915f4b13.png)
![image](https://user-images.githubusercontent.com/22101668/56333938-ce0fb480-61c8-11e9-8839-de82203ddcdd.png)
建议做个二级收放

**Comment by caspershw** [comment]
最新版已经添加。
