### ISSUE TITLE
很负责任的说：这是两个主题站上唯一最好用的一个

### ISSUE THREAD

**Issue by yifan792** [hiCasper/Typecho-theme-DUX#9]
测试过typecho.wiki和typecho.me上所有的主题，还是你这个主题最好，拿来就能用，就是可惜没有多级分类，能加上这个功能吗？

**Comment by caspershw** [comment]
感谢支持，二级分类折叠的问题抽空研究一下~

**Comment by yifan792** [comment]
二级分类折叠功能加进去了吗？

**Comment by heychriswu** [comment]
你好，
请问一下为何在安装主题时会提示缺少style.css的问题，我添加该文件后无法成功预览主题！

**Comment by caspershw** [comment]
一年后的回复：添加了
